auth.py
# Module und Klassen aus Flask werden importiert
from flask import Blueprint, render_template, redirect, url_for, flash, request

# Funktionen und Klassen aus Flask-Login und Werkzeug werden importiert
from flask_login import login_user, logout_user, current_user, login_required
from werkzeug.security import generate_password_hash, check_password_hash

# User-Modell, Registrieruns-Forms und DB-Verbindung werden importiert
from .models import User
from . import db, LoginManager
from .forms import RegistrationForm

# Blueprint für Authentifizierurng wird definiert
auth = Blueprint('auth', __name__)

# Funktion zum Laden eines Benutzers anhand seiner ID 
def load_user(user_id):
    return User.query.get(int(user_id))

# Route für die Registrierung von Benutzern
@auth.route('/register', methods=['GET', 'POST'])
def register():
    # RegistrationsForm-Objekt wird erstellt
    form = RegistrationForm()
    # Wenn Formular validiert wurde, indem Post-request mit Daten gesendet wurde, überprüfe, ob ein Benutzer mit dem angegebenen Benutzernamen bereits existiert 
    if form.validate_on_submit():
        existing_user = User.query.filter_by(username=form.username.data).first()
        # Wenn Benutzer existiert, dann Fehlermeldung ausgeben
        if existing_user:
            flash('The username is already taken. Please choose another one.', 'error')
        else:
            # Passwort wird gehasht mit pbkdf2: sha 256-Methode
            hashed_password = generate_password_hash(form.password.data, method='pbkdf2:sha256')
            # Neuen Benutzer erstellen und zur Datenbank hinzufügen
            new_user = User(username=form.username.data, password=hashed_password)
            db.session.add(new_user)
            db.session.commit()

            #Ausgabe einer Erfolgsmeldung und Weiterleitung zur Login-Page zum direkten Einloggen nach erfolgreichem Registrieren
            flash('Successfully registered! Please log in.', 'success')
            return redirect(url_for('views.index'))
    # Registerformular wird gerendert
    return render_template('register.html', form=form, signup_success=False)

# Route für die Überprüfung der Benutzer in der Datenbank zum Debuggen 
@auth.route('/check_database')
def check_database():
    # Alle Benutzer werden abgerufen
    all_users = User.query.all()

    # Ausgabe der Benutzerinformationen
    for user in all_users:
        print(f"ID: {user.id}, Username: {user.username}, Password: {user.password}")
    # Ausgabe einer Bestätigung
    return "Überprüfung der Datenbank abgeschlossen."

# Route zum Einloggen von Benutzern
@auth.route('/login', methods=['GET', 'POST'])
def login():
    #Wenn request empfangen wird und Formular gesendet wurde, nehme Benutzernamen und Passwort aus dem Formular
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')

        # Aussgabe der Anmeldeinformationen zum Debuggen 
        print(f"Received login request for username: {username}, password: {password}")
        
        #Abgleich des eingebenen Benutzernamens mit den Nutzern in der Datenbank
        user = User.query.filter_by(username=username).first()

        #Wenn Benutzer in DB nicht gefunden wurde, wird Fehlermeldung ausgegeben. Wenn doch, gib Benutzer und Passworthash aus (wieder zum Debuggen)
        if not user:
            flash('User not found. Please check your username.', category='error')
        else:
            print(f"User found in the database: {user.username}")
            print(f"Stored password hash: {user.password}")
        #PW wird mit gespeichertem PW-hash verglichen. Wenn PW korrekt, dann wird der Benutzer eingeloggt, direkt zur notes.html weitergeleitet und Erfolgsmeldung ausgegeben.
            if check_password_hash(user.password, password):
                login_user(user)
                flash('Successfully logged in!', category='success')
                return redirect(url_for('views.notes'))
            # Wenn PW inkorrekt eingegeben, dann wird eine Fehlermeldung ausgegeben.
            else:
                flash('Wrong password. Please try again', category='error')
    # Das Login-Formular wird gerendert
    return render_template('index.html', user=current_user)

# Route für das Ausloggen von Benutzern
@auth.route('/logout', methods=['GET', 'POST'])
def logout():
    # Logge den aktuellen Benutzer aus
    logout_user()

    # Gib eine Erfolgsmeldung aus und leite Benutzer zur Login Seite weiter.
    flash('Successfully logged out!', category='success')
    return redirect(url_for('auth.login'))

'''
### Kommentierter Code für die Weiterentwicklung im nächsten Sprint: Grundidee (noch nicht funktionsfähig) ###

from flask import render_template, redirect, url_for
from . import db, auth  # Replace 'your_flask_app' with the actual name of your Flask application
from .models import Note
from .forms import NoteForm

@auth.route('/create_note', methods=['GET', 'POST'])
@login_required  # Assuming you want to require login to create a note
def create_note():
    form = NoteForm()

    if form.validate_on_submit():
        # Create a new Note instance and save it to the database
        new_note = Note(
            placeholder1=form.placeholder1.data,
            placeholder2=form.placeholder2.data,
            placeholder3=form.placeholder3.data,
            placeholder4=form.placeholder4.data,
            placeholder5=form.placeholder5.data,
            user_id=current_user.id  # Assuming you have a user ID, replace it with the actual user ID
        )

        db.session.add(new_note)
        db.session.commit()

        return redirect(url_for('views.index'))  # Redirect to the index page or wherever you want to go after saving the note

    return render_template('create_note.html', form=form)
    '''

templates/base.html
<!DOCTYPE html>
<html lang="de">

<head>
    <!-- Zeichenkodierung wird gesetzt -->
    <meta charset="UTF-8">
    <!-- Fenster für Design wird gesetzt -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
        crossorigin="anonymous">
    <style>
        body {
            background-color: #87cefa;
        }
    </style>
    <title>{% block title %}Note Taking App{% endblock %}</title>
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='images/SimpleNote_logo.png') }}" />
</head>

<body>
    <!-- Flash-Nachrichten -->
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                {% if category == 'error' %}
                    <!-- Fehlermeldung -->
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        {{ message }}
                        <!-- Button fürs Schließen -->
                        <button type="button" class="close" data-dismiss="alert">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% else %}
                    <!-- Erfolgsmeldung -->
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ message }}
                        <!-- Schließen der Schaltfläche -->
                        <button type="button" class="close" data-dismiss="alert">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    {% endwith %}

    <!-- Hauptinhalt-Container -->
    <div class="container">
        <!-- Inhaltsblock -->
        {% block content %} {% endblock %}
    </div>

    <!-- Fußzeile -->
    <footer class="text-center bg-light text-muted fixed-bottom" style="height: 1.7cm;">
        <div style="background-color: rgba(0, 0, 0, 0.05); padding: 0.6cm;">
            <p class="mb-0">© 2024</p>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJ"
        crossorigin="anonymous"></script>
    <!-- Popper.js -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXUB6S3ZQKD7fpj9Bvv2SrfKTK7I4w9bFfF"
        crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>

</html>

templates/index.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block content %}

<div class="container-lg d-flex flex-column align-items-center justify-content-center my-5">
    <!-- SimpleNote Logo -->
    <img src="{{ url_for('static', filename='images/SimpleNote_logo.png') }}" alt="SimpleNote Logo" class="mb-4" width="350" height="220">
    <!-- Login-Formular -->
    <h3 class="mb-3"><strong>Login</strong></h3>
    <form method="POST" action="{{ url_for('auth.login') }}">
        <div class="form-group mb-5">
            <!-- Eingabefeld für den Benutzernamen -->
            <label for="username" style="font-size: 1.1em;"><strong>Name:</strong></label>
            <input type="text" class="form-control" id="username" name="username" placeholder="Name..." style="width: 480px; background-color: #cfe8f5;" required>
        </div>
        <div class="form-group mb-9 mt-3">
            <!-- Eingabefeld für das Passwort -->
            <label for="password" style="font-size: 1.1em;"><strong>Password:</strong></label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Password..." style="width: 480px; background-color: #cfe8f5;" required>
        </div>
        <!-- Link zur register.html = Registrierungsseite -->
        <p class="mt-1" style="font-style: italic; margin-bottom: 1cm;">Don't have an account? <a href="{{ url_for('auth.register') }}"><u>Create One!</u></a></p>
        <!-- Button zum Einloggen -->
        <div class="form-group d-flex justify-content-center mt-2">
            <button type="submit" class="btn btn-light rounded-pill px-5 py-3" style="background-color: #fff8dc; border: 1px solid black; font-size: 1.1em;"><strong>Log In!</strong></button>
        </div>
    </form>
</div>
{% endblock %}

templates/notes.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="./notesStyle.css" rel="stylesheet">
  <style>
          body {
            font-family: Arial, sans-serif;
            margin: 0;
            display: flex;
            flex-direction: column;
            min-height: 100vh;
        }

        .notes-container {
            display: flex;
            flex-direction: column;
            width: 50%;
            margin: 0 auto;
            flex: 1;
        }

        .notes-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 10px;
            background-color: #f0f0f0;
        }

        .header-content {
            display: flex;
            align-items: center;
        }

        .logo {
            margin-right: 20px;
        }

        .header-buttons button {
            margin-right: 10px;
        }

        .main-content {
            display: flex;
            flex: 2;
            flex-direction: row-reverse;
        }

        .notes-container2 {
            flex: 2;
            padding: 20px;
            order: 1;
        }

        .notes-container2 .placeholder {
            display: none;
        }
        

        .notes-sidebar {
            flex: 0.5;
            padding: 20px;
            background-color: #f0f0f0;
            order: 2;
        }

        .notes-nav button {
            display: block;
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
            text-align: left;
        }

        #AddPage {
            margin-top: 100px;
        }

        #Save {
            margin-left: 20px;
        }

        .notes-footer {
            display: flex;
            align-items: center;
            padding: 10px;
            background-color: #f0f0f0;
            margin-top: auto;
        }

        .notes-footer img {
            margin-right: 10px;
            border-radius: 50%;
        }

        .notes-text {
            margin-right: 10px;
        }

        .button {
            padding: 10px;
            background-color: #007bff;
            color: #fff;
            border: none;
            cursor: pointer;
        }

        .button:hover {
            background-color: #0056b3;
        }

        .notes-textarea {
            width: 100%;
            height: 600px;
            padding: 10px;
            box-sizing: border-box;
            margin-bottom: 20px;
        }

        .notes-button11 {
            background-color: #28a745;
        }

        .notes-button11:hover {
            background-color: #218838;
        }

        #Save {
          display: none;
          }

    </style>

</head>

<body>


  <div class="notes-container">
    <header id="Top" data-role="Header" class="notes-header">
      <div class="header-content">
        <img alt="logo" src="{{ url_for('static', filename='images/SimpleNote_logo.png') }}" alt="SimpleNote Logo" width="150" height="100" class="logo" />
        <div class="header-buttons">
        
      <!--Button für den text formatierung -->
          <button type="button" id="Normal" class="button" onclick="updateText('Normal')">Normal</button>
          <button type="button" id="Bold" class="notes-button01 button" onclick="updateText('Bold')">Bold</button>
          <button type="button" id="Underline" class="button" onclick="updateText('Underline')">Underline</button>
          <button type="button" id="StrikeThrough" class="button" onclick="updateText('StrikeThrough')">Strikethrough</button>

        </div>
      </div>
      <div data-role="MobileMenu" class="notes-mobile-menu"></div>
    </header>

    <div class="main-content">
      <div class="notes-sidebar">
        <nav class="notes-nav">
          <svg viewBox="0 0 1024 1024" class="notes-icon" width="20" height="20">
          </svg>
          
      <!--Buttonsfür den pages -->
          <button type="button" id="PageOne" class="notes-button04 button" onclick="showPlaceholder(1)">Page One</button>
          <button type="button" id="PageTwo" class="notes-button05 button" onclick="showPlaceholder(2)">Page Two</button>
          <button type="button" id="PageThree" class="notes-button06 button" onclick="showPlaceholder(3)">Page Three</button>
          <button type="button" id="PageFour" class="notes-button07 button" onclick="showPlaceholder(4)">Page Four</button>
          <button type="button" id="PageFive" class="notes-button08 button" onclick="showPlaceholder(5)">Page Five</button>
          <button type="button" id="AddPage" class="notes-button09 button" onclick="addPage()">Add Page</button>
         
          </nav>
      </div>
      <!--Platz halter für den pages -->
     
      <div class="notes-container2">
     <textarea name="placeholder1" id="placeholder1" placeholder="Placeholder 1" class="notes-textarea textarea placeholder"></textarea>
      <textarea name="placeholder2" id="placeholder2" placeholder="Placeholder 2" class="notes-textarea textarea placeholder"></textarea>
      <textarea name="placeholder3" id="placeholder3" placeholder="Placeholder 3" class="notes-textarea textarea placeholder"></textarea>
      <textarea name="placeholder4" id="placeholder4" placeholder="Placeholder 4" class="notes-textarea textarea placeholder"></textarea>
      <textarea name="placeholder5" id="placeholder5" placeholder="Placeholder 5" class="notes-textarea textarea placeholder"></textarea>
      </div>
    </div>
    <!--  logout button und save button-->
    <footer class="notes-footer">
    <img alt="image" src="{{ url_for('static', filename='images/SimpleNote_logo.png') }}" alt="SimpleNote Logo" width="100" height="100">
    <span class="notes-text">John Doe</span>
    <button type="button" id="Logout" class="button">Logout</button>
    
    <button id="Save" type="button" class="notes-button11 button">
        <span class="notes-text1">Save</span>
    </button>
</footer>


  </div>



  <script>
        function showPlaceholder(placeholderNumber) {
            // Alle platzhalter ausblenden
            for (let i = 1; i <= 5; i++) {
                document.getElementById(`placeholder${i}`).style.display = 'none';
            }

            // ausgewählte platz halter anzeigen
            document.getElementById(`placeholder${placeholderNumber}`).style.display = 'block';

            document.getElementById('Save').style.display = 'block';
        }

        function addPage() {
            console.log("Add Page clicked");
        }
    </script>

    <script type="text/javascript">
    //path to logout
document.getElementById("Logout").addEventListener("click", function() {
    window.location.href = "{{ url_for('auth.logout') }}";
});
</script>

<script>
        function addPage() {
            alert("Upgrade to premium to unlock all features!");
        }
        
</script>



<script>
 // Das richtige platzhalter anzeigen  entsprechen der selected page
    let activePlaceholder = 1;
    function showPlaceholder(placeholderNumber) {
        
        for (let i = 1; i <= 5; i++) {
            document.getElementById(`placeholder${i}`).style.display = 'none';
        }

        
        document.getElementById(`placeholder${placeholderNumber}`).style.display = 'block';
        activePlaceholder = placeholderNumber;

        document.getElementById('Save').style.display = 'block';
    }
// Popup Alert
    function addPage() {
        alert("Upgrade to premium to unlock all features!");
    }

    //Formatierungs des  Texts im Platzhalter
    function updateText(format) {
        const placeholder = document.getElementById(`placeholder${activePlaceholder}`);
        const currentText = placeholder.value;

        switch (format) {
            case 'Normal':
                placeholder.value = currentText;
                break;
            case 'Bold':
                placeholder.value = `**${currentText}**`;
                break;
            case 'Underline':
                placeholder.value = `_${currentText}_`;
                break;
            case 'StrikeThrough':
                placeholder.value = `~~${currentText}~~`;
                break;
            default:
                break;
        }
    }
</script>



</body>

</html>

templates/register.html
{% extends "base.html" %}
{% block title %}Sign Up{% endblock %}
{% block content %}

<!-- Registrierung - Erfolgsmeldung   -->
<div class="modal fade" id="signupSuccessModal" tabindex="-1" role="dialog" aria-labelledby="signupSuccessModalLabel" aria-hidden="True">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="signupSuccessModalLabel">Sign Up successful</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Your account has been successfully created!
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<!-- Formular für Sign-Up -->
<div class="container-lg d-flex flex-column align-items-center justify-content-center my-5">
    <img src="{{ url_for('static', filename='images/SimpleNote_logo.png') }}" alt="SimpleNote Logo" class="mb-4" width="350" height="220">
    <h3 class="mb-3"><strong>Sign Up</strong></h3>
    <form method="POST" action="{{ url_for('auth.register') }}">
        {{ form.hidden_tag() }}
        <div class="form-group mb-5">
            <label for="username" style="font-size: 1.1em;"><strong>Name:</strong></label>
            {{ form.username(class="form-control", placeholder="Name...", style="width: 480px; background-color: #cfe8f5;", required=True) }}
        </div>
        <div class="form-group mb-9 mt-3">
            <label for="password1" style="font-size: 1.1em;"><strong>Password:</strong></label>
            {{ form.password(type="password", class="form-control", placeholder="Password...", style="width: 480px; background-color: #cfe8f5;", required=True) }}
        </div>
        <div class="form-group mb-3 mt-1">
            <label for="password2" style="font-size: 1.1em;"><strong>Repeat Password:</strong></label>
            {{ form.confirm_password(type="password", class="form-control", placeholder="Password...", style="width: 480px; background-color: #cfe8f5;", required=True) }}
        </div>
        <p class="mt-1" style="font-style: italic; margin-bottom: 1cm;">Do you already have an account? <a href="{{ url_for('auth.login') }}"><u>Log In!</u></a></p> 
        <div class="form-group d-flex justify-content-center mt-2">
            {{ form.submit(class="btn btn-light rounded-pill px-5 py-3", style="background-color: #fff8dc; border: 1px solid black; font-size: 1.1em;") }}
        </div>
    </form>
</div>

{% endblock %}